### ISSUE TITLE
老师可以更新一下直接运行的版本吗

### ISSUE THREAD

**Issue by MayanoTopgun** [RnJ4/qndxx_batch_study#6]
发现不能用了就来看了一下，我看到那个main改了api什么的，但我毕竟不是计算机相关专业的，所以折腾了好久都不知道该怎么用，您可以更新一下那个exe运行的版本吗？实在是非常感谢！一直承蒙这个程序关照，帮大忙了

**Comment by RnJ4** [comment]
已更新

**Comment by MayanoTopgun** [comment]
伟大，无需多言，向您致敬
